server:
  port: ${SERVER_PORT:8080}

management:
  endpoint:
    health:
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /
      path-mapping.health: health
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

spring:
  kafka:
    producer:
      client-id: ${KAFKA_CLIENT_ID:order-service}
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      acks: all
      security.protocol: ${KAFKA_PROTOCOL:PLAINTEXT}
logging:
  level:
    org.apache.kafka.*: WARN

order-service:
  transport:
    billing:
      host: ${BILLING_HOST:http://localhost:8090}
      get-account-id: ${BILLING_GET_ACCOUNT_ID:api/v1/billing/account}
      patch-account: ${BILLING_PATCH_ACCOUNT_ID:api/v1/billing/account}
    topics:
      notification:
        notify: ${NOTIFICATION_TOPIC:notify}